@WEBAPIENTITYFRAMEWORK_HostAddress = https://localhost:7077

GET {{WEBAPIENTITYFRAMEWORK_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WEBAPIENTITYFRAMEWORK_HostAddress}}/api/superhero

###
